try {
    console.log(a);
} catch (err) {
   console.log(err);
}

var result= null;
console.log(result);


function  new1(a,b){
    console.log(a+b);
}
new1(10,"2");